// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqYRnSqzYFj2VhTBWgS9YBrbHggmaXMU',
    appId: '1:570322647130:web:f8857a29813bcaf9384063',
    messagingSenderId: '570322647130',
    projectId: 'jsrservices-9af06',
    authDomain: 'jsrservices-9af06.firebaseapp.com',
    storageBucket: 'jsrservices-9af06.appspot.com',
    measurementId: 'G-2DZV1LQLBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGP9qkAHOkwRi5divDoIkOdFaTMUmNz9Y',
    appId: '1:570322647130:android:6fd2c0ffff873d81384063',
    messagingSenderId: '570322647130',
    projectId: 'jsrservices-9af06',
    storageBucket: 'jsrservices-9af06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4FURhnK4p8Z3ziW_J_0OnhaZJ2XYDt0k',
    appId: '1:570322647130:ios:1e22de8108430a15384063',
    messagingSenderId: '570322647130',
    projectId: 'jsrservices-9af06',
    storageBucket: 'jsrservices-9af06.appspot.com',
    iosBundleId: 'com.example.jsrTiffin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4FURhnK4p8Z3ziW_J_0OnhaZJ2XYDt0k',
    appId: '1:570322647130:ios:0bf702fa99758a5b384063',
    messagingSenderId: '570322647130',
    projectId: 'jsrservices-9af06',
    storageBucket: 'jsrservices-9af06.appspot.com',
    iosBundleId: 'com.example.jsrTiffin.RunnerTests',
  );
}
